import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { HeroSection } from "@/components/home/HeroSection";
import { CategoryGrid } from "@/components/home/CategoryGrid";
import { FeaturedBiz } from "@/components/home/FeaturedBiz";
import { StatsStrip } from "@/components/home/StatsStrip";
import { RevistaSection } from "@/components/home/RevistaSection";
import { CTASection } from "@/components/home/CTASection";
import { supabase } from "@/lib/supabase";
